// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listAccounts: () => typedError<AccountDto[], MailError>(__TAURI_INVOKE("list_accounts")),
	getAccount: (id: number) => typedError<AccountDto, MailError>(__TAURI_INVOKE("get_account", { id })),
	createAccount: (request: CreateAccountRequest) => typedError<AccountDto, MailError>(__TAURI_INVOKE("create_account", { request })),
	updateAccount: (request: UpdateAccountRequest) => typedError<AccountDto, MailError>(__TAURI_INVOKE("update_account", { request })),
	deleteAccount: (id: number) => typedError<null, MailError>(__TAURI_INVOKE("delete_account", { id })),
	listEmails: (accountId: number, folder: string, page: number, limit: number) => typedError<EmailListResponse, MailError>(__TAURI_INVOKE("list_emails", { accountId, folder, page, limit })),
	// 按分类加载邮件列表
	listEmailsByCategory: (accountId: number, category: EmailCategory, page: number, limit: number) => typedError<EmailListResponse, MailError>(__TAURI_INVOKE("list_emails_by_category", { accountId, category, page, limit })),
	getEmail: (id: number) => typedError<EmailDetail, MailError>(__TAURI_INVOKE("get_email", { id })),
	searchEmails: (query: string, accountId: number | null, limit: number | null) => typedError<SearchResult[], MailError>(__TAURI_INVOKE("search_emails", { query, accountId, limit })),
	markAsRead: (emailId: number, isRead: boolean) => typedError<null, MailError>(__TAURI_INVOKE("mark_as_read", { emailId, isRead })),
	toggleStar: (emailId: number) => typedError<boolean, MailError>(__TAURI_INVOKE("toggle_star", { emailId })),
	deleteEmails: (emailIds: number[]) => typedError<number, MailError>(__TAURI_INVOKE("delete_emails", { emailIds })),
	moveEmailToFolder: (emailId: number, folder: string) => typedError<null, MailError>(__TAURI_INVOKE("move_email_to_folder", { emailId, folder })),
	sendEmail: (request: SendEmailRequest) => typedError<string, MailError>(__TAURI_INVOKE("send_email", { request })),
	syncAccount: (accountId: number) => typedError<null, MailError>(__TAURI_INVOKE("sync_account", { accountId })),
	getFolderStats: (accountId: number) => typedError<FolderStat[], MailError>(__TAURI_INVOKE("get_folder_stats", { accountId })),
	detectProvider: (email: string) => typedError<ProviderDetectionResult, MailError>(__TAURI_INVOKE("detect_provider", { email })),
	listProviders: () => typedError<ProviderInfo[], MailError>(__TAURI_INVOKE("list_providers")),
	startOauth2: (providerId: string, email: string, displayName: string | null) => typedError<OAuth2AuthUrl, MailError>(__TAURI_INVOKE("start_oauth2", { providerId, email, displayName })),
	pollOauth2: (state: string) => typedError<OAuth2PollResult, MailError>(__TAURI_INVOKE("poll_oauth2", { state })),
	updateAccountPassword: (id: number, password: string) => typedError<null, MailError>(__TAURI_INVOKE("update_account_password", { id, password })),
	listLabels: (accountId: number) => typedError<LabelDto[], MailError>(__TAURI_INVOKE("list_labels", { accountId })),
	createLabel: (request: CreateLabelRequest) => typedError<LabelDto, MailError>(__TAURI_INVOKE("create_label", { request })),
	updateLabel: (id: number, request: UpdateLabelRequest) => typedError<LabelDto, MailError>(__TAURI_INVOKE("update_label", { id, request })),
	deleteLabel: (id: number) => typedError<null, MailError>(__TAURI_INVOKE("delete_label", { id })),
	addLabelToEmail: (emailId: number, labelId: number) => typedError<null, MailError>(__TAURI_INVOKE("add_label_to_email", { emailId, labelId })),
	removeLabelFromEmail: (emailId: number, labelId: number) => typedError<null, MailError>(__TAURI_INVOKE("remove_label_from_email", { emailId, labelId })),
	getLabelsForEmail: (emailId: number) => typedError<LabelDto[], MailError>(__TAURI_INVOKE("get_labels_for_email", { emailId })),
	listEmailsByLabel: (labelId: number) => typedError<number[], MailError>(__TAURI_INVOKE("list_emails_by_label", { labelId })),
};

/** Events */
export const events = {
	syncProgressEvent: makeEvent<SyncProgressEvent>("sync-progress-event"),
};

/* Types */
export type AccountDto = {
	id: number,
	name: string,
	email: string,
	display_name: string | null,
	provider: string,
	color: string | null,
	sync_enabled: boolean,
	auth_type: string,
	account_type: string,
	last_sync_at: number | null,
	created_at: number,
};

export type AccountType = "Personal" | "Enterprise";

export type AuthType = "Password" | "OAuth2";

export type CreateAccountRequest = {
	name: string,
	email: string,
	display_name: string | null,
	provider: string,
	auth_type: string,
	password: string,
	imap_host: string | null,
	imap_port: number | null,
	imap_ssl_mode: string | null,
	smtp_host: string | null,
	smtp_port: number | null,
	smtp_ssl_mode: string | null,
	color: string | null,
	account_type: string | null,
};

export type CreateLabelRequest = {
	account_id: number,
	name: string,
	color: string,
};

/**
 *  邮件分类（前端侧边栏导航使用）
 * 
 *  每个变体对应 provider 的 `StandardFolder` 中的一组 IMAP 文件夹，
 *  `Starred` 例外 —— 它查询 `is_starred = true`（跨文件夹）。
 */
export type EmailCategory = "inbox" | "starred" | "sent" | "drafts" | "spam" | "trash" | "archive";

export type EmailDetail = {
	recipient_emails: string,
	cc_emails: string | null,
	body_text: string | null,
	body_html: string | null,
} & (EmailDto);

export type EmailDto = {
	id: number,
	account_id: number,
	folder: string,
	uid: number,
	subject: string | null,
	sender_name: string | null,
	sender_email: string,
	preview: string | null,
	is_read: boolean,
	is_starred: boolean,
	sent_at: number,
	has_attachments: boolean,
};

export type EmailListResponse = {
	emails: EmailDto[],
	total: number,
	page: number,
	limit: number,
};

export type FolderStat = {
	folder: string,
	total: number,
	unread: number,
};

export type LabelDto = {
	id: number,
	account_id: number,
	name: string,
	color: string,
};

// 统一错误类型 — 前端通过 tauri-specta Result 模式拿到类型化错误
export type MailError = { type: "AccountNotFound"; message: number } | { type: "AuthFailed"; message: string } | { type: "ImapConnectionFailed"; message: string } | { type: "SmtpSendFailed"; message: string } | { type: "SyncFailed"; message: string } | { type: "DatabaseError"; message: string } | { type: "KeyringError"; message: string } | { type: "ProviderNotSupported"; message: string } | { type: "InvalidParam"; message: string } | { type: "EmailNotFound"; message: number } | { type: "FolderNotFound"; message: string } | { type: "OAuthError"; message: string } | { type: "InvalidProvider"; message: string } | { type: "OAuth2Error"; message: string } | { type: "NotImplemented"; message: string } | { type: "LabelNotFound"; message: number } | { type: "ImapFolderMetadataFailed"; message: string } | { type: "ImapSearchFailed"; message: string } | { type: "BatchFetchHeadersFailed"; message: string } | { type: "ImapError"; message: string } | { type: "EmailMissingUid" };

// OAuth2 授权 URL 结果
export type OAuth2AuthUrl = {
	url: string,
	state: string,
	port: number,
};

// OAuth2 授权完成信息（返回给前端的最小信息）
export type OAuth2CompletedInfo = {
	email: string,
};

// OAuth2 轮询状态
export type OAuth2PollResult = "Pending" | ({ Completed: OAuth2CompletedInfo }) & { Error?: never } | ({ Error: string }) & { Completed?: never };

export type ProviderDetectionResult = {
	detected: boolean,
	provider_id: string | null,
	provider_name: string | null,
	auth_types: string,
};

export type ProviderInfo = {
	id: string,
	name: string,
	account_type: AccountType,
	domains: string[],
	auth_type: AuthType,
	color: string | null,
	icon: string | null,
	sort_order: number,
};

export type SearchResult = {
	id: number,
	account_id: number,
	folder: string,
	subject: string | null,
	sender_email: string,
	sent_at: number,
	preview: string | null,
	rank: number,
};

export type SendEmailRequest = {
	account_id: number,
	to: string[],
	cc: string[],
	bcc: string[],
	subject: string,
	body_html: string,
	body_text: string,
};

export type SyncProgress = {
	account_id: number,
	stage: SyncStage,
	folder: string | null,
	current: number,
	total: number,
	message: string,
};

export type SyncProgressEvent = {
	progress: SyncProgress,
};

export type SyncStage = "Connecting" | "SyncingFolders" | "SyncingEmails" | "Completed" | "Error";

export type UpdateAccountRequest = {
	id: number,
	name: string | null,
	display_name: string | null,
	color: string | null,
	sync_enabled: boolean | null,
};

export type UpdateLabelRequest = {
	name: string | null,
	color: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

